RHEcosystemAppEng/cluster-iq

- Makefile
- cmd/api/api_server.go
- go.mod
- go.sum
- internal/logger/logger.go
Created a separated package to return the Zap logger already configured with standard options and env config vars, predefined for this project
> Logger configuration by an internal package

- README.md
- cmd/api/api_server.go
- deployments/openshift/api.yaml
- deployments/openshift/console.yaml
- deployments/openshift/scanner.yaml
- internal/stocker/aws.go
Added Instances endpoint to retrieve every instances inventored
> Added Instances endpoint

- cmd/api/api_server.go
> Added API endpoint to obtain clusters by name

- cmd/api/mock_server.go
- internal/inventory/account_test.go
- internal/inventory/cluster.go
- internal/inventory/cluster_test.go
- internal/stocker/aws.go
> Added accountName to inventory.Cluster object

- Makefile
- open_api_design.yaml
Adds a YAML file about the OpenAPI design for Swagger Editor
> Added OpenAPI design by @vbelouso

- Makefile
- cmd/api/api_server.go
- cmd/scanner/scanner.go
- deployments/docker-compose/docker-compose.yaml
- deployments/dockerfiles/Dockerfile-api
- deployments/dockerfiles/Dockerfile-scanner
- internal/stocker/aws.go
- internal/stocker/azure.go
- internal/stocker/gcp.go
> Generic scanner

- cmd/api/api_server.go
- Add endpoint to retrieve instances specific to the cluster
Necessary for frontend (UI - `Clusters` - `<ClusterName> ` -  `Servers` tab)
> add getClusterInstances endpoint

- cmd/api/api_server.go
- cmd/api/handlers.go
- cmd/api/responseTypes.go
Closes #70 
chore: Added healthcheck endpoint to API
> chore: Added healthcheck endpoint to API

- Makefile
- cmd/api/api_server.go
- cmd/api/db.go
- cmd/api/db_types.go
- cmd/api/handlers.go
- cmd/api/responseTypes.go
- db/sql/clean.sql
- db/sql/init.sql
- db/sql/test_data.sql
- db/test_files/new-expense.json
- db/test_files/new-instance.json
- internal/inventory/account.go
- internal/inventory/account_test.go
- internal/inventory/cluster.go
- internal/inventory/cluster_test.go
- internal/inventory/common.go
- internal/inventory/expense.go
- internal/inventory/expense_test.go
- internal/inventory/instance.go
- internal/inventory/instance_test.go
- internal/inventory/inventory.go
- internal/inventory/inventory_test.go
- internal/inventory/types.go
- internal/inventory/types_test.go
- internal/stocker/aws.go
- open_api_design.yaml
Closes #65 
Added Expenses logic and data structures to ClusterIQ for tracking expenses of each server / cluster tracking the billing API of the cloud provider
> Expenses data structures and logic

- doc/development-setup.md
> docs: add additional validaton steps

- Makefile
> chore: add dependency validation for required binaries

- README.md
- cmd/scanner/scanner.go
- internal/inventory/account.go
> Added billing flag to Account. Billing module is disabled by default

- internal/inventory/types.go
Signed-off-by: Vladimir Belousov <vbelouso@redhat.com>
> fix: correct type for InstanceStatus constants

- cmd/api/api_server.go
- cmd/api/handlers.go
- Add stubs for cluster power management
Future implementation will be available after discussing the `executor` architecture.
> feat: add cluster power management handlers

- Makefile
- deployments/compose/compose-devel.yaml
- fix SELinux volumes permissions
- always pull container images from repository
> fix:  always pull container images from repository

- Makefile
- deployments/compose/compose-devel.yaml
> chore: makefile standardization 

- internal/cloud_providers/aws/aws-ec2.go
Adds `getInstanceCreationTimestamp` function to retrieve the EC2 instance 
creation timestamp based on the root block device attach time.
Signed-off-by: Vladimir Belousov <vbelouso@redhat.com>
> fix: correctly determine EC2 instance creation timestamp

- cmd/api/handlers.go
- cmd/api/router.go
- cmd/api/server.go
- internal/middleware/middlware.go
* Split routes into separate functions for better organization
* Add proper signal handling with graceful shutdown
* Move server lifecycle functions (Start/Run) to dedicated methods
* Implement force quit on repeated interrupt signals
* Configure Gin middleware
> chore: reorganize server structure and improve shutdown handling

- internal/cloud_providers/aws/aws-cost-explorer.go
Fixed CostExplorer service client creation
> fix: Assigned CostExplorer service client connection correctly

- cmd/api/router.go
@vbelouso noticed a typo on the "SetupSwagger" function.
Fixed and merging
> fix: typo on function 'setupSwagger'

- .github/workflows/container-image-building.yaml
- .github/workflows/go-lint-and-format.yml
- .golangci.yaml
Added GitHub Actions workflow for linting and formatting.
> feat: code linting, formatting using GH actions

- README.md
- cmd/api/router.go
- cmd/scanner/scanner.go
- db/sql/init.sql
- deployments/compose/compose-devel.yaml
- deployments/helm/cluster-iq/templates/database/job
- deployments/helm/cluster-iq/templates/scanner/configmap.yaml
- deployments/helm/cluster-iq/values.yaml
- internal/cloud_executors/aws.go
- internal/cloud_providers/aws/aws-ec2.go
- internal/config/scanner_config.go
- internal/inventory/account.go
- internal/inventory/cluster.go
- internal/inventory/tag.go
- internal/inventory/types.go
- internal/models/models.go
- internal/sql_client/sql_client.go
- internal/sql_client/sql_queries.go
- internal/stocker/aws_stocker.go
- internal/stocker/aws_stocker_ec2.go
> Release 0.4.1

- cmd/scanner/scanner.go
- internal/stocker/aws_billing.go
* Fixed logging information on AWS Billing Stocker.
* Modified validStockers list management because it was excluding the billing stocker
* Added `skippedAccounts` var because substracting account and stockers result is not correct if the billing stockers are enabled
Closes #162
> bug: account detail billing

- .github/workflows/build-container-images.yaml
- .github/workflows/integration-tests.yaml
- .github/workflows/unit-tests.yaml
- .github/workflows/validate-pr.yaml
- .gitignore
- Makefile
- deployments/compose/compose-gh.yaml
- test/integration/api_test.go
Refactor GHActions workflows including unit and Integration tests
> Refactor GHActions workflows

- internal/models/models.go
- internal/sql_client/sql_queries.go
Closes #203 
Related to [ClusterIQ Console #101](https://github.com/RHEcosystemAppEng/cluster-iq-console/issues/101)
> feat: Added instances summary by states to overview API endpoint
